# Generated by Django 2.0.3 on 2018-04-03 07:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SunovionEvent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('requestor_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=10)),
                ('duration', models.PositiveSmallIntegerField()),
                ('participants_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('presenters_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('producer_required', models.BooleanField(default=False)),
                ('rehearsal_required', models.BooleanField(default=False)),
                ('recording_required', models.BooleanField(default=False)),
                ('technology_check', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('presenters', models.TextField(blank=True)),
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('reviewed', 'reviewed'), ('accepted', 'accepted')], default='new', max_length=100, no_check_for_status=True)),
                ('reviewed_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'reviewed'})),
                ('accepted_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'accepted'})),
            ],
            options={
                'ordering': ['-modified', '-created'],
            },
        ),
    ]
