# Generated by Django 2.0.3 on 2018-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunovion_events', '0004_auto_20180403_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunovionevent',
            name='period',
            field=models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='am', max_length=5),
        ),
    ]
