import uuid

from django.db import models
from model_utils.models import TimeStampedModel


class Event(TimeStampedModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    event_code = models.CharField(max_length=50)
    internal_cal_id = models.CharField(max_length=50, blank=True)
    event_name = models.CharField(max_length=50, blank=True)
    project_code = models.CharField(max_length=50, blank=True)
    customer = models.CharField(max_length=50, blank=True)
    event_status = models.CharField(max_length=50, blank=True)
    start_time = models.CharField(max_length=50, blank=True)
    duration = models.CharField(max_length=50, blank=True)
    prod_start = models.CharField(max_length=50, blank=True)
    prod_hours = models.CharField(max_length=50, blank=True)
    producers_req = models.CharField(max_length=50, blank=True)
    invite_coming = models.CharField(max_length=50, blank=True)
    on_site = models.CharField(max_length=50, blank=True)
    site_address = models.CharField(max_length=50, blank=True)
    lead_contact = models.CharField(max_length=50, blank=True)
    contact_phone = models.CharField(max_length=50, blank=True)
    contact_email = models.EmailField(blank=True)
    link_needed = models.CharField(max_length=50, blank=True)
    exp_participants = models.CharField(max_length=50, blank=True)
    exp_presenters = models.CharField(max_length=50, blank=True)
    presenters_list = models.TextField(blank=True)
    report_reqs = models.CharField(max_length=50, blank=True)
    record_reqs = models.CharField(max_length=50, blank=True)
    original_request = models.URLField(blank=True)
    meeting_link = models.URLField(blank=True)
    meeting_user = models.EmailField(blank=True)
    meeting_password = models.CharField(max_length=50, blank=True)
    audio_type = models.CharField(max_length=50, blank=True)
    tc_number = models.URLField(blank=True)
    tc_participant_pin = models.CharField(max_length=50, blank=True)
    tc_host_pin = models.CharField(max_length=50, blank=True)
    scheduled_by = models.CharField(max_length=50, blank=True)
    production_ready = models.CharField(max_length=50, blank=True)
    prod_one_id = models.CharField(max_length=50, blank=True)
    prod_one_email = models.EmailField(blank=True)
    prod_one_confirm = models.CharField(max_length=50, blank=True)
    prod_two_id = models.CharField(max_length=50, blank=True)
    prod_two_email = models.EmailField(blank=True)
    prod_two_confirm = models.CharField(max_length=50, blank=True)
    event_code_numeric = models.CharField(max_length=50, blank=True)
    cal_name = models.CharField(max_length=50, blank=True)
    docs_link = models.URLField(blank=True)
    prod_one_cell = models.CharField(max_length=50, blank=True)
    prod_two_cell = models.CharField(max_length=50, blank=True)
    client_event_code = models.CharField(max_length=50, blank=True)
    assigned_by = models.CharField(max_length=50, blank=True)
    client_invite_link = models.URLField(blank=True)
    internal_notes = models.TextField(blank=True)
    client_notes = models.TextField(blank=True)
    internal_event_link = models.URLField(blank=True)
    end_time = models.CharField(max_length=50, blank=True)
    project_id = models.CharField(max_length=100, blank=True)
    portal_link = models.URLField(blank=True)

    class Meta:
        ordering = ['-modified', '-created']
