# Generated by Django 2.0.3 on 2018-04-22 12:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiogenEvent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('requestor_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('period', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='am', max_length=5)),
                ('duration', models.PositiveSmallIntegerField()),
                ('participants_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('presenters_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(choices=[('US/Central', 'US/Central'), ('US/Eastern', 'US/Eastern'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific')], default='US/Eastern', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('presenters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('reviewed', 'reviewed'), ('accepted', 'accepted')], default='new', max_length=100, no_check_for_status=True)),
                ('reviewed_at', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'reviewed'})),
                ('accepted_at', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'accepted'})),
                ('eod_webcast', models.CharField(choices=[('EOD', 'EOD'), ('Webcast', 'Webcast')], max_length=20)),
                ('ms_sma', models.CharField(choices=[('MS', 'MS'), ('MSA', 'MSA')], max_length=20)),
                ('slide_deck_name', models.CharField(blank=True, max_length=255)),
                ('slide_deck_id', models.CharField(blank=True, max_length=255)),
                ('program_meeting_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Biogen Event',
                'verbose_name_plural': 'Biogen Events',
                'ordering': ['-modified', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(choices=[('2018-001-Nov', '2018.001 Nov - Legal 2018 Support'), ('2018-002-Bio', '2018.002 Bio - EOD HCP and SMA PEP Programs'), ('2018-003-Nov', '2018.003 Nov PLS 1st'), ('2018-005-Ver', '2018.005 Ver - VAKO 2018'), ('2018-007-Nov', '2018.007 Nov - Post ENETS 2018'), ('2018-008-Sun', '2018.008 Sun - Training Studio Session Support'), ('2018-008-01-Sun', '2018.008.01 Sun - Sainz January Fast Start'), ('2018-008-02-Sun', '2018.008.02 Sun - January New Hire Training'), ('2018-008-03-Sun', '2018.008.03 Sun - The Hospital Expert'), ('2018-008-04', '2018.008.04 Studio Maintenance'), ('2018-008-05-Sun', '2018.008.05 Sun - April New Hire Phase II'), ('2018-009-Nov', '2018.009 Nov - Onc VA Reimagining Access Meeting'), ('2018-011-Nov', '2018.011 Nov - Onc IDAPS Meeting'), ('2018-012-Nov', '2018.012 Nov - PLS IDAPS'), ('2018-013-Nov', '2018.013 Nov - Onc MA IDAPS'), ('2018-014-Nov', '2018.014 Nov - MMS Support Plan'), ('2018-015-Nov', '2018.015 Nov - Onc Franchise Head Sessions'), ('2018-016-Bio', '2018.016 Bio - WW Medical Speaker Meetings'), ('2018-018-Nov', '2018.018 Nov - Onc International Broadcast'), ('2018-019-Bio', '2018.019 Bio - FFT Training'), ('2018-020-Ver', '2018.020 Ver - Multi event contract'), ('2018-021-Nov', '2018.021 Nov - Additional Legal Support'), ('2018-022-Bio', '2018.022 Bio - Marketing Sessions'), ('2018-023-Bio', '2018.023 Bio - MS Patient Webinars'), ('2018-024-Nov', '2018.024 Nov - Segmented Marketing'), ('2018-025-GE', '2018.025 GE - NPI August')], max_length=255, unique=True)),
                ('client', models.CharField(blank=True, choices=[('Novartis', 'Novartis'), ('Biogen', 'Biogen'), ('Vertex', 'Vertex'), ('Sunovion', 'Sunovion'), ('GE', 'GE')], max_length=100)),
                ('fulfilled_by', models.CharField(blank=True, choices=[('Intempio', 'Intempio'), ('RVibe', 'RVibe')], max_length=100)),
                ('sow_status', models.CharField(blank=True, choices=[('Client', 'Client'), ('Signed', 'Signed')], max_length=100)),
                ('invoice_sheet', models.CharField(blank=True, max_length=255)),
                ('invite_sent_by', models.CharField(blank=True, choices=[('Intempio', 'Intempio'), ('RVibe', 'RVibe')], max_length=100)),
                ('invite_type', models.CharField(blank=True, choices=[('single', 'single'), ('recurring', 'recurring')], max_length=50)),
                ('run_sheet', models.BooleanField(default=False)),
                ('reporting', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-modified', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SunovionEvent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('requestor_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('period', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='am', max_length=5)),
                ('duration', models.PositiveSmallIntegerField()),
                ('participants_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('presenters_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(choices=[('US/Central', 'US/Central'), ('US/Eastern', 'US/Eastern'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific')], default='US/Eastern', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('presenters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('reviewed', 'reviewed'), ('accepted', 'accepted')], default='new', max_length=100, no_check_for_status=True)),
                ('reviewed_at', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'reviewed'})),
                ('accepted_at', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'accepted'})),
                ('producer_required', models.BooleanField(default=False)),
                ('rehearsal_required', models.BooleanField(default=False)),
                ('recording_required', models.BooleanField(default=False)),
                ('technology_check', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Project')),
            ],
            options={
                'verbose_name': 'Sunovion Event',
                'verbose_name_plural': 'Sunovion Events',
                'ordering': ['-modified', '-created'],
            },
        ),
        migrations.AddField(
            model_name='biogenevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Project'),
        ),
    ]
