# Generated by Django 2.0.3 on 2018-04-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sunovionevent',
            options={'ordering': ['-modified', '-created'], 'verbose_name': 'Sunovion Event', 'verbose_name_plural': 'Sunovion Events'},
        ),
    ]
