# Generated by Django 2.0.3 on 2018-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0002_auto_20180425_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=255),
        ),
    ]
