# Generated by Django 2.0.3 on 2018-04-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_biogenevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biogenevent',
            old_name='docs_link',
            new_name='slide_deck_name',
        ),
    ]
