# Generated by Django 2.0.3 on 2018-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0003_auto_20180425_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=255),
        ),
    ]
