# Generated by Django 2.0.3 on 2018-05-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0005_historicalbiogenevent_historicalsunovionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogenevent',
            name='producer_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biogenevent',
            name='recording_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biogenevent',
            name='rehearsal_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biogenevent',
            name='technology_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbiogenevent',
            name='producer_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbiogenevent',
            name='recording_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbiogenevent',
            name='rehearsal_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbiogenevent',
            name='technology_check',
            field=models.BooleanField(default=False),
        ),
    ]
