# Generated by Django 2.0.3 on 2018-05-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0006_auto_20180501_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogenevent',
            name='eod_webcast',
            field=models.CharField(blank=True, choices=[('EOD', 'EOD'), ('Webcast', 'Webcast')], max_length=20),
        ),
        migrations.AlterField(
            model_name='biogenevent',
            name='ms_sma',
            field=models.CharField(blank=True, choices=[('MS', 'MS'), ('MSA', 'MSA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbiogenevent',
            name='eod_webcast',
            field=models.CharField(blank=True, choices=[('EOD', 'EOD'), ('Webcast', 'Webcast')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbiogenevent',
            name='ms_sma',
            field=models.CharField(blank=True, choices=[('MS', 'MS'), ('MSA', 'MSA')], max_length=20),
        ),
    ]
